test:
  image: python:3.7
  script:
  - pip install tox
  - tox -e py37,lint

eslint:
  image: "registry.gitlab.com/eyeo/docker/adblockplus-ci:node10"
  script:
  - npm install -g eslint
  - npm install eslint-config-eyeo
  - eslint wentral/vis_ui/visualization.js

pages:
  stage: deploy
  image: python:3.7
  script:
  - pip install mkdocs-material
  - cp LICENSE.txt  docs/
  - cp README.md  docs/
  - cp .gitlab-ci.yml docs/gitlab-ci.yml
  - sed -i "s/(\.gitlab-ci.yml)/(gitlab-ci.yml)/g" docs/README.md
  - mkdir docs/docs
  - cp docs/*.md docs/docs
  - cp -r docs/img/ docs/docs

  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master

