##################################

#Project documentation for Wentral

##################################

site_name: Wentral
site_url: 
site_description: Wentral Project documentation with Markdown.
site_author: Eyeo GmBH

repo_url: 

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - python
    logo: img/eyeo_like_robot-transparent-256.png
    favicon: img/eyeo_like_robot-white-256.png

nav:
    - Overview: README.md
    - Command line usage : cli.md
    - API : api.md
    - File Formats : file-formats.md



copyright: Copyright &copy; <script>document.write(new Date().getFullYear())</script> <a href="https://www.eyeo.com">Eyeo GmBH</a>.

plugins:
    - search
