name: Build Documentation using MkDocs 
# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch 
on: 
  push: 
    branches: [master] 
  pull_request: 
    branches: [master] 
jobs: 
  build: 
    name: Build and Deploy Documentation 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Master 
        uses: actions/checkout@v2 
      - name: Set up Python 3.7 
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.x' 
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install mkdocs-material
      - name: Deploy 
        run: | 
          git pull 
          cp LICENSE.txt  docs/
          cp README.md  docs/
          cp .gitlab-ci.yml docs/gitlab-ci.yml
          sed -i "s/(\.gitlab-ci.yml)/(gitlab-ci.yml)/g" docs/README.md
          mkdir docs/docs
          cp docs/*.md docs/docs
          cp -r docs/img/ docs/docs
          mkdocs gh-deploy
